### ISSUE TITLE
无法识别除3*3外的合成表

### ISSUE THREAD

**Issue by jhqwqmc** [iXanadu13/SlimeFunRecipe#1]
无法识别除3*3外的合成表

**Comment by iXanadu13** [comment]
Can you give an example?
比如哪种粘液物品？

**Comment by jhqwqmc** [comment]
粘液附属的算吗

**Comment by jhqwqmc** [comment]
![image](https://user-images.githubusercontent.com/113768629/235973871-71e33e2c-2ab1-4296-9a03-9de1c4a8f091.png)
![image](https://user-images.githubusercontent.com/113768629/235973896-bd904a5a-6b16-407f-ab24-a76e93f8ca4d.png)
例如 InfinityExpansion 无尽科技 的无尽头盔

**Comment by iXanadu13** [comment]
据我所知，所有粘液科技本体的物品配方都可以在3x3之内表示，所以目前采用的是3x3规格。
后续可以考虑兼容更多粘液附属。
另外，可以发我一下你在用的无尽科技插件吗，给个网址就行，我有空了去尝试下兼容

**Comment by jhqwqmc** [comment]
https://builds.guizhanss.cn/SlimefunGuguProject/InfinityExpansion/master

**Comment by jhqwqmc** [comment]
这个

**Comment by jhqwqmc** [comment]
就是说如果能识别这个物品的合成表大小可能会兼容性广一点

**Comment by iXanadu13** [comment]
等我有空了会尝试兼容无尽科技的，感谢您的建议。
但可能需要等一段时间吧，因为马上就要期中考试了。
I'm so sorry about that...

**Comment by jhqwqmc** [comment]
好的，其实不止是无尽科技，这里的部分附属都有涉及超过3*3的合成表
https://slimefun-wiki.guizhanss.cn/Addons?id=official-addons

**Comment by iXanadu13** [comment]
使用1.1.0版本

**Comment by iXanadu13** [comment]
使用1.1.0版本。
