### ISSUE TITLE
Infinity expansion

### ISSUE THREAD

**Issue by BomasJ** [iXanadu13/SlimeFunRecipe#2]
Can you make the infinity workbench recipes editable?
![image](https://github.com/iXanadu13/SlimeFunRecipe/assets/139186644/f239f779-b87a-4d4f-a05b-d632c8dde5bf)

Addon Name: Infinity Expansion
Addon: https://github.com/Mooy1/InfinityExpansion
Download: https://thebusybiscuit.github.io/builds/Mooy1/InfinityExpansion/master/

**Comment by iXanadu13** [comment]
I will try to support Infinity Expansion.
Thanks for your suggestion.

**Comment by iXanadu13** [comment]
Using v1.1.0.
