### ISSUE TITLE
无法编辑头颅物品

### ISSUE THREAD

**Issue by Clexus** [iXanadu13/SlimeFunRecipe#5]
如题，你可以拿一个碳试试

**Comment by iXanadu13** [comment]
怎么不行了？
碳的配方，8个煤炭改4个：
<details>

![Snipaste_2024-05-30_00-06-54](https://github.com/iXanadu13/SlimeFunRecipe/assets/104714710/60765a9a-54be-4123-b73a-7fd7fae8250b)
</details>

<details>

![Snipaste_2024-05-30_00-10-26](https://github.com/iXanadu13/SlimeFunRecipe/assets/104714710/fa738674-ba80-4c82-b2a9-e7850129c83a)
<details>
